
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserService", targetNamespace = "http://metier/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserService {


    /**
     * 
     * @param iduser
     * @param login
     * @param nom
     * @param prenom
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://metier/", className = "service.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://metier/", className = "service.UpdateUserResponse")
    @Action(input = "http://metier/UserService/updateUserRequest", output = "http://metier/UserService/updateUserResponse")
    public String updateUser(
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom,
        @WebParam(name = "login", targetNamespace = "")
        String login,
        @WebParam(name = "iduser", targetNamespace = "")
        int iduser);

    /**
     * 
     * @return
     *     returns java.util.List<service.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllUser", targetNamespace = "http://metier/", className = "service.GetAllUser")
    @ResponseWrapper(localName = "getAllUserResponse", targetNamespace = "http://metier/", className = "service.GetAllUserResponse")
    @Action(input = "http://metier/UserService/getAllUserRequest", output = "http://metier/UserService/getAllUserResponse")
    public List<User> getAllUser();

    /**
     * 
     * @param password
     * @param login
     * @param nom
     * @param prenom
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addUser", targetNamespace = "http://metier/", className = "service.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://metier/", className = "service.AddUserResponse")
    @Action(input = "http://metier/UserService/addUserRequest", output = "http://metier/UserService/addUserResponse")
    public String addUser(
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom,
        @WebParam(name = "login", targetNamespace = "")
        String login,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param password
     * @param login
     * @return
     *     returns service.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "userLogin", targetNamespace = "http://metier/", className = "service.UserLogin")
    @ResponseWrapper(localName = "userLoginResponse", targetNamespace = "http://metier/", className = "service.UserLoginResponse")
    @Action(input = "http://metier/UserService/userLoginRequest", output = "http://metier/UserService/userLoginResponse")
    public User userLogin(
        @WebParam(name = "login", targetNamespace = "")
        String login,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param iduser
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://metier/", className = "service.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://metier/", className = "service.DeleteUserResponse")
    @Action(input = "http://metier/UserService/deleteUserRequest", output = "http://metier/UserService/deleteUserResponse")
    public String deleteUser(
        @WebParam(name = "iduser", targetNamespace = "")
        int iduser);

}
